### ISSUE TITLE
Moving generation code to new repo

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mvt-fixtures#11]
My feeling is that `mvt-fixtures` should be:

  - easy to regenerate from pure code (e.g. not depend on any upstream data sources)
  - each fixture should be extremely small and single purpose (contain a single feature, or geometry)
  - achieve full coverage of the valid spec with the minimal amount of bytes

In line with this, and in order to keep the repo size small, what do you think about moving the generation code to another repo? Then `mvt-fixtures` would represent just the fixture data (and downloading it you'd only get the data). I think the generation code lives inside `_reserve`?

**Comment by mapsam** [comment]
Good question - I haven't had the time to clean up `_reserve`, and didn't want to just get rid of it. I'm hesitant to move it to another repo since that'll make updating between repos/projects more difficult than necessary. 

Unless we see mvt-fixtures as complete, in that case I say we get rid of it for good. We can always add the generation code as a gist to use again another time.

**Comment by springmeyer** [comment]
Okay. Let's close this then and focus on getting complete. Next action there would be https://github.com/mapbox/mvt-fixtures/issues/8. Can you write up a mini-document on how to add a fixture and I'll take a look at knocking out https://github.com/mapbox/mvt-fixtures/issues/8  in the process?
