### ISSUE TITLE
Validity of 003

### ISSUE THREAD

**Issue by joto** [mapbox/mvt-fixtures#33]
Spec says "A feature MUST contain a type field as described in the Geometry Types section." This could be "UNKNOWN" [which is okay](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4341-unknown-geometry-type). The [proto file](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L41) sets the default of this field to UNKNOWN. So arguably if this is not set in the file, it is still set to 0 which still means it is set. If this wasn't the case, why have the default value at all? So I think, according to the spec the 003 fixture is valid.

Same issue with 009 and the extent.

**Comment by mapsam** [comment]
@joto thanks for raising this! Just so I understand, even if the geometry field (field `3`) is completely missing, this is considered valid?

Right now the raw dump of the buffer shows that the geometry `3` field isn't present: 

```
3 {
  15: 2
  1: "hello"
  2 {
    1: 1
    2: ""
    4: "\t2\""
  }
  5: 4096
}
```

Perhaps a better way to describe this fixture is "Feature is completely missing geometry `3` field. Since default is 0, encoders should assume UNKNOWN geometry type".

**Comment by joto** [comment]
@mapsam Yes, this is how I would see it. And your description is spot on.

@flippmoke Any opinions?

**Comment by flippmoke** [comment]
@joto Isn't default enforced on the decoding side not the encoding side if it is not present? This is probably a good test for something using protozero for certain?

**Comment by joto** [comment]
@flippmoke Yes, we are talking about the decoding side. So this test doesn't put the GeomType field into the tile to make the decoder fail, becase the spec says the tile must have a GeomType. But any normal vector tile decoder would look at this and say there is a GeomType there, because the underlying protobuf lib would give it the default GeomType of UNKNOWN. In proto2 you can check whether you got the default or not, but that's an extra check you have to do. In proto3 this is not possible any more, because protobuf 3 will never put the default value of anything in the actual tile data.

**Comment by GretaCB** [comment]
Related to https://github.com/mapbox/mvt-fixtures/pull/42, similarly given a default depending on the decoder. 

Does the `proto` property serve as a good way to verify the validity of these types of fixtures? Or should there be some extra logic somewhere to handle these finnicky default values?

**Comment by mapsam** [comment]
> any normal vector tile decoder

So vtzero will set the default, but any protozero-based decoder that doesn't see the .proto file will consider this invalid. I think I'm going to mark "invalid" since the validity fields are based on the version of the spec rather than the version of the proto parser. That said - it feels important to note these "what's invalid to the vt spec may not be invalid to proto2 parsers due to defaults" notes to the README. I'll write up a section and make a PR.

**Comment by mapsam** [comment]
Now in the README 

> GOTCHA: validity can be messy. In the case of the validity property for the fixtures, they refer to the Mapbox Vector Tile Specification but depending on the protocol buffer specification we are decoding with, fields that may be required by the spec and are missing can be interpreted as default values. For example: in fixture 003 where the "GeomType" tag is completely missing, any vector tile decoder using the proto2 syntax will interpret this by the default value UNKNOWN instead of a missing tag.
