### ISSUE TITLE
Packaging the vector-tile-spec submodule in npm packages

### ISSUE THREAD

**Issue by mapsam** [mapbox/mvt-fixtures#61]
just published 3.0.0-beta2 and installed it elsewhere to use the `.get()` method, but getting the following error:

```
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir 'vector-tile-spec'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.<anonymous> (/Users/mapsam/mapbox/vtquery/node_modules/@mapbox/mvt-fixtures/lib/generateBuffer.js:9:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mapsam/mapbox/vtquery/node_modules/@mapbox/mvt-fixtures/index.js:7:24)
```

This makes sense, since the vector-tile-spec directory is a submodule and therefore doesn't get packaged with npm. Not sure of the exact route around this, but [first SO search](https://stackoverflow.com/questions/15279703/using-non-npm-package-git-submodules-in-npm-packages#15282866) doesn't look promising.

cc @springmeyer

**Comment by springmeyer** [comment]
Ideas that come to mind:

 - a) Vendor the `vector-tile-spec` inside mvt-fixtures git repo instead of using a submodule
 - b) Package the `vector-tile-spec` as an npm module
 - c) Add a build step to `mvt-fixtures` to copy the `vector-tile-spec` submodule to a custom location that will get packaged when you run `npm publish`
 - d) require downstream users of the `mvt-fixtures` API to add the `vector-tile-spec` git submodule. I presume the % of users that actually need the submodule will be small, right? Since most users are non-Js libraries that will pull in the fixtures by file path rather than the JS API?

**Comment by mapsam** [comment]
@springmeyer I'm in favor of `a` - that feels like the most fail-proof/easiest-to-maintain considering how infrequently the spec changes. I'll work on an update!

**Comment by springmeyer** [comment]
> @springmeyer I'm in favor of a

👍

**Comment by mapsam** [comment]
The submodule was not the issue - the real issue is how the path is referenced [on this line](https://github.com/mapbox/mvt-fixtures/blob/95ca09141a8d96bc181cf234ff96906ef795ebb1/lib/generateBuffer.js#L9-L11). I'll work on a fix for this tomorrow!
